[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Encoding = "gzip"