
[build]
  publish = "Build" # ou o diretório onde estão seus arquivos estáticos

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"
    Cache-Control = "max-age=31536000" # cache prolongado

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[build.processing]
  css = false
  js = false
