[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "gzip"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Content-Encoding = "gzip"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html"
    Content-Encoding = "gzip"
