[build]
  publish = "Build"

[[headers]]
  for = "/Build/*.gz"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "gzip"

[[headers]]
  for = "/Build/*.br"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Encoding = "br"
